### ISSUE TITLE
Reset colors after using gradient!

### ISSUE THREAD

**Issue by eliassjogreen** [tomakita/Colorful.Console#23]

**Comment by tomakita** [comment]
Thanks for the idea.  Just so I'm sure that I understand, would it be possible to explain your use case in more detail?  In particular: what is the behavior you're after, and why?

**Comment by eliassjogreen** [comment]
'''C#
Console.WriteWithGradient("Hello world!".ToCharArray(), Color.Yellow, Color.Fuchsia, 14);

Console.ResetColor(); // the foreground color is still Color.Fuchsia instead of being the default!

Console.Write("Hello world!"); //This is still Color.Fuchsia and not the default color (gray).

Console.ForegroundColor = Color.Gray; //Should set the foreground color to gray but still doesnt seem to work!

Console.Write("Hello world!"); //This is still Color.Fuchsia and not gray.
'''

Good luck!
Sorry if my english isnt the best!

**Comment by eliassjogreen** [comment]
```C#
Console.WriteWithGradient("Hello world!".ToCharArray(), Color.Yellow, Color.Fuchsia, 14);

Console.ResetColor(); // the foreground color is still Color.Fuchsia instead of being the default!

Console.Write("Hello world!"); //This is still Color.Fuchsia and not the default color (gray).

Console.ForegroundColor = Color.Gray; //Should set the foreground color to gray but still doesnt seem to work!

Console.Write("Hello world!"); //This is still Color.Fuchsia and not 
```

Good luck!
Sorry if my english isnt the best!

**Comment by tomakita** [comment]
Ok, this sounds like a bug.  I'll take a look into this over the weekend, and will update this thread with my findings.  Thanks for the report!

**Comment by tomakita** [comment]
Apologies, I should have caught this earlier!  The issue is that once you've manipulated the console's color palette with `Colorful.Console` methods, `System.Console.ResetColor` might not do exactly what you had expected.  To be more specific: `System.Console.ResetColor` will set the console's foreground and background colors to their defaults.  The default would normally be gray, BUT if `Colorful.Console` has been used to manipulate the color palette, the color in the console's "default color" array index might not be gray.  In your case, it sounds like the default color has been overwritten as fuchsia.

So instead of `System.Console.ResetColor`, try `Colorful.Console.ReplaceAllColorsWithDefaults`, e.g.:

```csharp
using Console = Colorful.Console;

Console.WriteWithGradient(chars, Color.Yellow, Color.Fuchsia, 14);
Console.ReplaceAllColorsWithDefaults(); // replace all colors with their defaults
```

Alternatively, `Colorful.Console.ReplaceColor(Color oldColor, Color newColor)` can be used to replace a specific color with a different color.

Let me know if that helps!
