### ISSUE TITLE
Advertising The Project

### ISSUE THREAD

**Issue by RehanSaeed** [tomakita/Colorful.Console#3]
http://blogs.msdn.com/b/dotnet/archive/2016/01/12/the-week-in-net-1-12-2015.aspx

**Comment by tomakita** [comment]
This is awesome!!  I'm not sure if you had a hand in that or not, but thanks a bunch either way -- maybe more people will contribute now!

**Comment by RehanSaeed** [comment]
I suggested the project last week.

**Comment by tomakita** [comment]
Cool, thanks for helping to spread the word about the project!

1. The colors in the icon could definitely be brighter.  I'll experiment with this and may end up making the change.
2. This is a great idea, and will be next on my list of things to add.  Actually, I also need to work on the tests that have already been written, because I just switched the project from .csproj to .xproj, and it's turning out to be hard to find a testing framework that works with DNX.  I was using NUnit before, but it doesn't seem to support DNX, yet.  I have a feeling that this will change pretty quickly, though.
3. This sounds like an awesome idea, and I would be very interested in this sort of a contribution, because I don't have much time to add this functionality myself.  I'll take a closer look at gsscoder's command line parser that you linked to, but do you think that we might be able to modify it for our purposes (giving him credit, of course, if he's OK with that)?  

On the other hand, starting from scratch seems like it would be pretty fun, but I'm probably not the one who's going to be doing it, so it's probably not my decision.

Anyway, thanks again for your help.  I just released a new version (1.0.4) of the NuGet package, and your name is now in the Authors section.  Just let me know if you want me to add it anywhere else!

**Comment by RehanSaeed** [comment]
I use xUnit which has proper support for DNX projects. NUnit has fledgling support but you have to use the command line to run the tests. Install the SideWaffle VS extension to get a DNX unit test project template.

I looked at the source code for that project and it's pretty big. There are other projects too but none give you the chance to style console output or are as fully featured as the project I linked. I started writing my own simpler version, not sure when I'll get it done if ever.

Nice work, keep it up.

**Comment by tomakita** [comment]
Ok cool, I'll check out xUnit over the weekend -- thanks for the recommendation.

Nice work to you too!
