### ISSUE TITLE
Colorful.Console is overloading Console.Write and printing newlines when it should not.

### ISSUE THREAD

**Issue by hephinator** [tomakita/Colorful.Console#33]
Code: 

```
static void Main(string[] args)
        {
            Console.Write("{0,-32} ", args[0], Color.LightGray);
            Console.Write("ONLINE", Color.FromArgb(0, 0, 255, 0));

            Console.Write(Environment.NewLine);
            Console.Write(Environment.NewLine);
            Console.Write(Environment.NewLine);

            Console.Write("{0,-32} ", args[0]);
            Console.Write("ONLINE", Color.FromArgb(0, 0, 255, 0));
        }
```

Resulting output: http://i.imgur.com/s1aoPAd.png

This should NOT be happening. No newline character (\n) was in the string format specifier, and Console.Write does NOT newline by default (thats what we have Console.WriteLine) for.

This only happens when you do not specify a color option as part of the overload.

**Comment by tomakita** [comment]
Thanks for raising this issue.  This has been fixed in https://github.com/tomakita/Colorful.Console/commit/9e62dca8898be01c795adb04d0380f9d8bd83284, but has not yet been included in a NuGet package release.  I'll release an updated version of the package in the next day or so, and will update this thread when it's online -- sorry for the inconvenience!

**Comment by hephinator** [comment]
Awesome! Thanks for the update!
<3

**Comment by tomakita** [comment]
The NuGet package with this bug fix has been published!

https://www.nuget.org/packages/Colorful.Console/1.1.0

Thanks for waiting!
