### ISSUE TITLE
WriteWithGradient() causes issues with further calls to WriteLine()

### ISSUE THREAD

**Issue by DoctorLogiq** [tomakita/Colorful.Console#56]
After calling
`Console#WriteWithGradient(...)`
some strange behaviour can occur when trying to set the colour back to white.

In my particular case, I write with a gradient, write with the colour Gray, then write with the colour White, and the text which should be white is rendered using a colour from the gradient (seems to also be a little inconsistent as to which colour is sampled).

I think the only way to explain this is with a simple screenshot, so:

![210c88c05bf6487f312468a3d4793601](https://user-images.githubusercontent.com/32243802/56445053-3bb7ff80-62f3-11e9-94b4-6c3e65039377.png)

OS Information: Windows 10 Pro 64-bit, version 1809, build 17763.437

**Comment by tomakita** [comment]
Thanks for the question.  This is expected behavior (see [usage notes](https://github.com/tomakita/Colorful.Console#usage-notes) -- what's happening here is that the console (pre-Windows 10 virtual terminal, which Colorful.Console doesn't yet support) can only write in a total of 16 different colors in a session.  Once 16 different colors are used, and you try to write with a 17th color, one of the 16 colors that were previously used will be used, instead of that 17th color.

For more details, see https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorManager.cs

For the status of the aforementioned virtual terminal support, see https://github.com/tomakita/Colorful.Console/issues/24
