### ISSUE TITLE
Is there BackgroundColor parametr in Console.Write()?

### ISSUE THREAD

**Issue by TuTAH1** [tomakita/Colorful.Console#80]
Why there's no Background setting, but only Foreground? I would like to write `Write("string",SomeTextColor,SomeBackgroundColor)`, but I didn't found that in `Colorful.Console.Write()`

**Comment by tomakita** [comment]
Great question.  You can set the background color, but it's done like this:

`Console.BackgroundColor = Color.Aquamarine;`
`Console.Write("string", Color.BlueViolet);`

That will write `string` with a foreground color of BlueViolet, and a background color of Aquamarine.  The reason it's done that way is because that's how it's done in the System.Console API, and Colorful.Console tries to retain the same API, where possible.
