### ISSUE TITLE
Written color overwriting default color of console.

### ISSUE THREAD

**Issue by ghost** [tomakita/Colorful.Console#81]
![Broken](https://i.ibb.co/yBRJ0VW/sad2.png)

I can't even write another color to the console because it overwrites everything. Oh well!  
I'm using my library ColorUtility which generates gradients for me. It works well, but the printing does not.  

Please update this project to support .NET core projects.

**Comment by tomakita** [comment]
Hi, would it be possible to add more detail to your post?  E.g. a higher-resolution screenshot (I can't read what's in the attached screenshot), or a code snippet that reproduces your issue?

Thanks!

**Comment by ghost** [comment]
Okay.

For file 1 (Program.CS):

```cs
using ColorUtility;
using System;
using System.Collections.Generic;
using System.Drawing;

namespace GradientGen {
  class Program {
    static int Main(string[] args) {
      Action < string[] > gradientGen = (internalArgs) => {
        Color fromColor = internalArgs[0].ParseFromRGB();
        Color toColor = internalArgs[1].ParseFromRGB();

        int steps = Convert.ToInt32(internalArgs[2]);

        List < Color > colors = ColorControls.GetColorGradient(fromColor, toColor, steps);

        Console.WriteLine();
        Console.WriteLine("COLOR GRADIENT");
        Console.WriteLine();

        foreach(Color color in colors)
        Colorful.Console.Write($"{ColorUtility.ColorConverter.ToARGBHex(color)} ", color);

        Console.ResetColor();
      };

      gradientGen.TryRunAction(args);

      return 69420;
    }
  }
}
```
(Yes this really does return 69420 and it doesnt break the program)

For file 2 (Extensions.CS):

```cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GradientGen {
  public class Exception: System.Exception {
    public static Exception Null = null;
  }

  public static class Extension {
    public static Exception TryRunAction(this Action < string[] > action, string[] arg) {
      try {
        action.Invoke(arg);
        return Exception.Null;
      } catch (Exception e) {
        return e;
      }
    }

    public static Color ParseFromRGB(this string rgbColor) {
      int[] colorParsed = rgbColor.Split(',').ToIntArray();
      return Color.FromArgb(colorParsed[0], colorParsed[1], colorParsed[2]);
    }

    public static int[] Rotate(this int[] arr, int offset) {
      var l = arr.Length;
      var rot = new int[l];

      if (offset == 0) {
        Array.Copy(arr, 0, rot, 0, l);
        return rot;
      }
      offset = offset % l;

      if (offset < 0)
        offset += l;

      Array.Copy(arr, offset, rot, 0, l - offset);
      Array.Copy(arr, 0, rot, l - offset, offset);

      return rot;
    }

    public static int[] ToIntArray(this string[] stringArray) {
      return Array.ConvertAll(stringArray, int.Parse);
    }
  }
}
```

The console output when I run the command ```gradientgen 0,0,255 255,0,0 100``` is all visibly ```0,0,255```

**Comment by ghost** [comment]
This is the image of the console after running the command
![Sad](https://i.ibb.co/vm8R2FN/sad33.png)

**Comment by tomakita** [comment]
Thanks.  

Does the `steps` variable (`internalArgs[2]`) control how many different colors you expect to be in the gradient?  If so, I imagine that is the problem.  On Windows, you can only write in 16 different colors in a single console session (see the [note](https://github.com/tomakita/Colorful.Console#usage-notes) at the end of the README).  If you try writing in more colors than that, the behavior that you'll see is undefined.

Can you try lowering the `steps` value to e.g. 5, and see what happens?

**Comment by ghost** [comment]
Okay, looks like it works I guess?

![Sadge](https://i.ibb.co/fYNFvMQ/sad44.png)

But why was it overwriting the default white console color? Everything printed was just blue.
I couldn't even change the color or reset it.

**Comment by tomakita** [comment]
Cool.

It overwrites the default console color because, (simplifying a bit) there are 16 slots in which colors can be stored in a console session.  Two of those colors are used when you start a session with the default Windows settings (black for the background, and white for the foreground).  Colorful.Console will allow you to overwrite the colors in those two initial slots, and that's why the white in your foreground turns to a different color.

When that happens, you can't change any of the colors or reset them, because there is no way for Colorful.Console to know which of its own colors it should map to which color slots.  If you're curious to know how that works, take a look at:

- https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorManager.cs
- https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorMapper.cs

Btw, I'm not sure if this will help you, but Colorful.Console has its own gradient writer: https://github.com/tomakita/Colorful.Console#style-collections-with-a-gradient
